server.port=${PORT:8080}
spring.application.name=engine
app.cors.allowed-origins=http://localhost:3000,https://learningplatform-dvdyxxuxf-yasha0111s-projects.vercel.app,https://learningplatform-pbl.vercel.app,https://learningplatform-pbl-java.vercel.app
